### PR TITLE
Added new buypass test root certificate

### PR DESCRIPTION
**Pull request by shamglam**
Buypass has added a new root certificate for test - for "enterprise certifcates". 

New "enterprise certificates" (for testing) issued by Buypass are having issues when used with Digipost Signering because they are trusting this root certificate. 

This PR adds this new root certificate to this library.

https://buypassdev.atlassian.net/wiki/spaces/BCA/pages/2195062891/Rotsertifikater+Root+certificates+test

G2 - third item.

### CODE REVIEW

**Comment by runeflobakk** [comment]
Thank you for the heads-up on this! I will look into it as soon as I have the time.

Just to understand properly, Buypass has started issuing enterprise certificates (virksomhetssertifikater) for testing from an entirely separate and new certificate hierarchy, i.e. both root and CA certificate?

**Comment by shamglam** [comment]
As i understand it, we got an enterprise certificate for testing, but the trust chain was issued using a root certificate which buypass - at the time of issuance hadn't added to their list on confluence - it was added at a later time.

I suppose given the chain of trust the "intermediate CA" is also issued by this new root certificate.

the intermediate CA has thumbprint c2e6cb59628657d713f2e1f344a744377bd5e3a6

**Comment by runeflobakk** [comment]
I will need to investigate a bit here, because "the third item", the file your PR is replacing, is the root certificate for the "Soft Token" CA, which we already have in our trust store, and in operation on servers in our test environments, and we originally got these from Buypass (obviously). It just seems strange that Buypass would silently replace a complete root and CA chain. Granted, it is "just" a test CA-chain, but still... a bit unusual. If this is the case, our servers would need to trust both the existing CA-chain, as well as the allegedly new chain.

I will compare what we already are using with the certificates currently offered for download from Buypass, and if necessary also ask Buypass about this matter, and get back to you.

I assume you are trying to use the [.NET client lib](https://github.com/difi/sikker-digital-post-klient-dotnet) and the client refuses to use your enterprise certificate because it fails validation in the client? Just to eliminate any misconfig or other anomalies, did you try to disable the client validating your certificate, as described here?
https://signering-docs.readthedocs.io/en/latest/client-integration/create-client-configuration.html#create-client-configuration
```c#
CertificateValidationPreferences = { ValidateSenderCertificate = false }
```
The client/sender's certificate will be validated by the server in any case, so disabling this is not a security issue. The client will also still validate the certificate used by the API/server, maintaining the expected mutual TLS handshake protocol. The validation happens only to offer a fail-fast to avoid attempting to connect to the API with an invalid certificate, and is only there as a convenience, and safe to turn off.

**Comment by shamglam** [comment]
just so we are on the same page
"third item" being https://crt.test4.buypassca.com/BPCl3RootCaG2ST.cer
and having a thumbprint of abba804a59cf8f5da060e13ffbd263e3d02e486b

I'm not sure if "replaced" is the correct term - more like they issued an enterprise certificate - which the .net library doesn't trust, and when I talked to buypass support they said they forgot to add information about the root certificate being used for this on their confluence site. 

Since it is not in the .net library and not documented in confluence  - I assumed it was a "new" root certificate .
and if you already have this root certificate in trust store it might be that only the .net library forgot to add this. 

And yes - disabling client side validation fixes the issue at hand.

**Comment by runeflobakk** [comment]
> And yes - disabling client side validation fixes the issue at hand.

Ah, that's what I was hoping to hear! 😅 

This particular certificate file is [already present](https://github.com/digipost/api-client-shared-dotnet/tree/main/Digipost.Api.Client.Shared/Resources/Certificate/Data/TestChain) as `BPCl3RootCaG2ST.cer`, and has been for two years. Your PR would replace this file, not add it. 

In fact, all the SEIDv2-certs has been [loaded since api-client-shared-dotnet v7.1.0](https://github.com/digipost/api-client-shared-dotnet/commit/f7a4937998701831cdf22771213ff5c3871a93b4), and the client library has supported this since [v8.1.0](https://github.com/digipost/signature-api-client-dotnet/releases/tag/8.1.0). Are you using v8.1.0 or newer of this library?

**Comment by shamglam** [comment]
looking at this again, you are indeed correct that the library contains the root certificate already - I was so fixed on the fact that it was missing that I didn't notice that my PR would replace an existing file.

Also the fact that buypass hadn't publically informed about this root certificate also put my on this wild goose chase.

That being said - part of my analysis was looking at the compiled digipost dlls in Dotpeek to see what certificates were in the code and looking at it again I noticed that the dll version is 6.0.0 - which is an old version of this library.

I created a new blank test console application referring to digipost signature library 9.0.3 and noticed that after compiling - .net is still downloading/using Digipost.Api.Client.Shared.dll 6.0.0.0 so something isn't adding up correctly.
Is it possible that this is caused by the fact that the Digipost Signature dlls are missing assembly version information?

**Comment by shamglam** [comment]
@runeflobakk I haven't heard from you in a while ... are you following this issue up?

**Comment by runeflobakk** [comment]
@shamglam It may be, as you say, that there are indeed erroneous assembly version information in the shared library.
I see that it is declared as 6.0.0.0, so I suspect they have not been updated since the v6 release or so.
https://github.com/digipost/api-client-shared-dotnet/blob/7.1.3/SolutionItems/AssemblyInfo.cs#L7-L8

I have passed this one to a colleague, as I have started my x-mas vacation.

**Pull request closed without merging**
